### ISSUE TITLE
Unable to Configure Two-Factor User Settings on Greebo

### ISSUE THREAD

**Issue by nosbig** [wilminator/dokuwiki-plugin-twofactor#9]
I had a test wiki from the previous release of Dokuwiki which was presenting the "Two-Factor Settings" link next to my user link in the upper-right corner of the screen.  After upgrading to the latest release of DW (Greebo), this link never appears next to my user link.

**Comment by ffito** [comment]
I'm having this same issue with Greebo. TwoFactor admin page is showing only one user, and not even him can see the TwoFactor Settings link.
Email plugin worked with his account though, but not with others.

**Comment by Draky50110** [comment]
Fresh install of Greebo : same problem.
One of 2FA plugins is (are) not compatible with Greebo :(

**Comment by Ryonez** [comment]
I'm not the only one then. No link for users to set up the plugin on their end.

**Comment by wilminator** [comment]
I'm looking into the Greebo anomaly. @Ryonez, please clarify "never worked properly". We are discontinuing use of doku at work :( but I want to see this keep working for now.

**Comment by Ryonez** [comment]
The user link to access the TwoFactor configuration page is nowhere to be found.

I can enforce it, which makes it appear when they log in next, but I want it as opt-in. And they have no way to do so without that link.

**Comment by wilminator** [comment]
@Ryonez thanks for the additional info.  I will look into it more.

**Comment by wilminator** [comment]
Short answer- Dokuwiki changed how to add menu items the end of last year.  I'm working on replacing what broke now while leaving the old code in for backwards compatibility.

**Comment by wilminator** [comment]
Okay, the menu change I made is running on my development box.  I have released it.  Please update and confirm that the menu is working for you as well.

@Ryonez I am now looking into what you are seeing.  Might be a couple days, but I will try to get this wrapped up for you.

**Comment by Ryonez** [comment]
@wilminator 
I feel this was closed prematurely, as we hadn't even reported back on the outcome.

The link still doesn't appear for me. I'm not even sure where it's meant to be. Just in case it was the template (bootstrap3), I set it back to dokuwiki, with no success.

**Comment by wilminator** [comment]
Sorry about that, and you are right about me needing to leave it open for feedback.
Please confirm the version of DokuWiki you are using; this can be found by following the directions posted at https://www.dokuwiki.org/faq:version

**Comment by wilminator** [comment]
@nosbig  thanks for the confirmation.  If I can get a couple more confirms I will update the official DW page to support Greebo.

**Comment by ffito** [comment]
I'll try to confirm tomorrow.
Just wanted to add that I'm running Frusterick and it works ok, but not with Bootstrap template. I have to use the default template for the TwoFactor Settings link to show up. I guess that's a Bootstrap issue

**Comment by Draky50110** [comment]
I confirm that with default template and Greebo, it works perfectly with the last release/commits.
Menu item is ok.

**Comment by wilminator** [comment]
@ffito Which bootstrap module(s) are you using?

**Comment by wilminator** [comment]
@Ryonez I think I have found a problem with the bootstrap3 template.  I need to do more digging to confirm, but it appears that the author has hard-coded the entries in the user menu.  I want to research this a little more to confirm what I'm seeing and see if I can help fix this issue rather than just throw this problem over their way.

**Comment by Ryonez** [comment]
@wilminator So it would show from just having the extension active then.

Would explain why trying to use the default template didn't change anything.

**Comment by ffito** [comment]
@wilminator I was using bootstrap3 template, but as it failed (and I really needed TwoFactor) I uninstalled it, can't remember now how it was configured

**Comment by wilminator** [comment]
I have posted my bootstrap3 [patch file](https://gist.github.com/wilminator/bca27f8866c9b380c7ec535d3e0b66c4).  It is a one line addition, so it's not too difficult to hack in by hand if you want to try it.

**Comment by ffito** [comment]
I've just seen this, thanks!. We updated to Greebo and it's working fine with the latest version of Twofactor. Our wiki is in production now, and I no longer have access to the server, but I'll test the patch in a vm if I have some time

**Comment by ffito** [comment]
Not sure if this is related, but I have another issue: I'm only using the Google Authenticator module (Email module is installed but disabled), and when the sessions time out, Twofactor asks for a verification code that is not the one from Google auth. It seems to be the email code, but none is sent to the  user address (which is normal, since that module it's not configured)

![image](https://user-images.githubusercontent.com/35381419/42057406-947d89ac-7af3-11e8-833f-237cc6cf137c.png)

**Comment by wilminator** [comment]
@ffito That is related to #10 and I thought I had released a fix for it.  Please follow up with this specific issue there.

**Comment by wilminator** [comment]
I discovered an error in the email module that broke it for login.  This has been fixed and the update released.

**Comment by wilminator** [comment]
@Draky50110 I have pushed another change that should address your notification problem.  I have also reworked the workflow to better handle turning on and off the twofactor module at large.  This should also ensure that you are prompted for a password when you login and have anything configured and ready to go.  Please confirm.  Thanks!

**Comment by wilminator** [comment]
Last call for further problems with this issue.

**Comment by ffito** [comment]
So far so good. Couldn't test it with Bootstrap though, can anyone confirm if it works?

**Comment by 3ruce** [comment]
This doesn't work with the bootstrap template but it works fine with the default template.... Everything has been freshly installed today....
